### ISSUE TITLE
Issues with running the program

### ISSUE THREAD

**Issue by aleu785** [bioinfomaticsCSU/SCOP#1]
Hi bioinfomaticsCSU

I am interested in running the SCOP program. However, i have come across some errors:

LD_LIBRARY_PATH=/home/leu2/SCOP/bamtools_path/lib/ /home/leu2/SCOP/SCOP   scaffolds.fasta maxbin.107.1500.assembly.007.fasta.fa.R1.fastq maxbin.107.1500.assembly.007.fasta.fa.R2.fastq 150 116.9 0.15 0.2 2 1 0 result
create path failed!
path:result/mapping/SCOP_alignScript_corr0.sh
bash: result/mapping/SCOP_alignScript_corr0.sh: No such file or directory
python /home/leu2/SCOP/contigClassify.py -bam result/mapping/correction_sort0.bam -a 0.4 -b 0.5 -m 116 -s 17 -i scaffolds.fasta -o result/mapping/correctionContig.fasta
Traceback (most recent call last):
  File "/home/leu2/SCOP/contigClassify.py", line 6, in <module>
    import parse_bam as pb
  File "/home/leu2/SCOP/parse_bam.py", line 6, in <module>
    import numpy as np
ImportError: No module named numpy
python /home/leu2/SCOP/contigSort_origin.py result/mapping/correctionContig.fasta result/mapping/correctionContig1.fasta
Traceback (most recent call last):
  File "/home/leu2/SCOP/contigSort_origin.py", line 6, in <module>
    tmp_file = open(tmppath, "w")
IOError: [Errno 2] No such file or directory: 'result/mapping/correctionContig1.fasta'
path:result/mapping/SCOP_alignScript0.sh
bash: result/mapping/SCOP_alignScript0.sh: No such file or directory
result/mapping/correctionContig1.fasta
Open File Wrong!

Any idea what i am doing wrong?

Thanks!

**Comment by devil-cry** [comment]
You can create PATH by yourself, and copy all SCOP files to your dataset. Like this: 

mkdir s_scop
cd s_scop/
echo readlen=$read_len

mkdir $sname
cp ~/tools/scaffolding/SCOP/* .

SCOP ../../contigs.fa ../../../left.fastq ../../../right.fastq $read_len $ins_mean 0.07 0.2 2 0 0 $sname
